version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "@netlabs/devops"
    assignees:
      - "@netlabs/devops"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"

  # Docker dependencies (Containerfile)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "@netlabs/devops"
    assignees:
      - "@netlabs/devops"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    # Only update patch and minor versions for base images
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # If package.json exists (Node.js dependencies)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@netlabs/developers"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
      - "automated"
    # Group development dependencies
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "jest*"
          - "typescript*"
        update-types:
          - "minor"
          - "patch"

  # If requirements.txt exists (Python dependencies)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@netlabs/developers"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "automated"
    # Allow both requirements.txt and any requirements/ directory
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"