# Hadolint configuration for Dockerfile/Containerfile linting
---
failure-threshold: warning
format: json

# Ignore specific rules that may not apply to bootc images
ignored:
  # DL3008: Pin versions in apt get install (not applicable to dnf/yum)
  - DL3008
  # DL3009: Delete the apt-get lists (not applicable to dnf/yum)
  - DL3009

# Override some rules for RHEL/bootc specific patterns
override:
  # Allow dnf instead of yum
  - error: DL3033
    reason: "dnf is preferred over yum in RHEL 9+"
  
  # Allow specific patterns for bootc images
  - error: DL3059
    reason: "Multiple consecutive RUN instructions are acceptable for bootc layer optimization"

# Trusted registries for base images
trustedRegistries:
  - "registry.redhat.io"
  - "registry.access.redhat.com"
  - "quay.io/redhat"

# Label schema validation
labelSchema:
  # Required labels for container metadata
  maintainer:
    required: false
    description: "Container maintainer information"
  
  version:
    required: false
    description: "Container version"
    
  description:
    required: false
    description: "Container description"

# Allowed instructions (all standard Docker instructions)
# This can be restricted if needed for security compliance
allowedInstructions: []

# Strict label key format (optional)
strictLabels: false